"""
Deployment script for Expeta-generated blog website

This script sets up and runs the Flask blog application generated by Expeta.
It also creates necessary data directories and sample content.
"""

import os
import json
import sys
from datetime import datetime

os.chdir(os.path.dirname(os.path.abspath(__file__)))

def setup_sample_data():
    """Create sample data for the blog"""
    print("Setting up sample data...")
    
    os.makedirs('data', exist_ok=True)
    
    blog_posts = [
        {
            "id": "post1",
            "title": "Getting Started with Web Design",
            "content": "Web design is the process of creating websites. It encompasses several different aspects, including webpage layout, content production, and graphic design.",
            "excerpt": "Learn the basics of web design and how to get started on your journey.",
            "date": "2025-04-01",
            "author": "Jane Doe",
            "featured_image": "https://via.placeholder.com/800x400?text=Web+Design",
            "categories": ["Design", "Web Development"],
            "comments": [
                {
                    "name": "John Smith",
                    "email": "john@example.com",
                    "content": "Great article! Very helpful for beginners.",
                    "date": "2025-04-02 14:30:00"
                }
            ]
        },
        {
            "id": "post2",
            "title": "Color Theory in UI Design",
            "content": "Color theory is both the science and art of using color. It explains how humans perceive color; and the visual effects of how colors mix, match or contrast with each other.",
            "excerpt": "Discover how to use color theory to create more effective and appealing user interfaces.",
            "date": "2025-04-05",
            "author": "Jane Doe",
            "featured_image": "https://via.placeholder.com/800x400?text=Color+Theory",
            "categories": ["Design", "UI/UX"],
            "comments": []
        },
        {
            "id": "post3",
            "title": "Responsive Design Principles",
            "content": "Responsive web design is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes.",
            "excerpt": "Learn the key principles of responsive design to ensure your websites work on all devices.",
            "date": "2025-04-10",
            "author": "Jane Doe",
            "featured_image": "https://via.placeholder.com/800x400?text=Responsive+Design",
            "categories": ["Design", "Web Development", "Mobile"],
            "comments": []
        }
    ]
    
    portfolio_items = [
        {
            "id": "project1",
            "title": "E-commerce Website Redesign",
            "description": "A complete redesign of an e-commerce platform focusing on user experience and conversion optimization.",
            "image": "https://via.placeholder.com/800x600?text=E-commerce+Redesign",
            "category": "Web Design",
            "client": "Fashion Retailer",
            "date": "2025-03-15",
            "featured": True
        },
        {
            "id": "project2",
            "title": "Mobile App UI Design",
            "description": "User interface design for a fitness tracking mobile application with a focus on clean, intuitive controls.",
            "image": "https://via.placeholder.com/800x600?text=Mobile+App+UI",
            "category": "UI/UX",
            "client": "Health Tech Startup",
            "date": "2025-02-20",
            "featured": True
        },
        {
            "id": "project3",
            "title": "Brand Identity Design",
            "description": "Complete brand identity including logo, color palette, typography, and brand guidelines.",
            "image": "https://via.placeholder.com/800x600?text=Brand+Identity",
            "category": "Branding",
            "client": "Organic Food Company",
            "date": "2025-01-10",
            "featured": False
        }
    ]
    
    with open('data/blog_posts.json', 'w') as f:
        json.dump(blog_posts, f, indent=2)
    
    with open('data/portfolio_items.json', 'w') as f:
        json.dump(portfolio_items, f, indent=2)
    
    print("✅ Sample data created successfully")

def create_missing_templates():
    """Create any missing template files needed for the blog"""
    print("Creating missing template files...")
    
    templates_dir = 'templates'
    
    required_templates = [
        'about.html', 
        'blog_post.html', 
        'contact.html', 
        'portfolio.html', 
        'portfolio_item.html'
    ]
    
    existing_templates = os.listdir(templates_dir)
    
    for template in required_templates:
        if template not in existing_templates:
            print(f"Creating missing template: {template}")
            
            if template == 'about.html':
                content = """<!DOCTYPE html>
<html>
<head>
    <title>About - My Personal Website</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home') }}">Home</a></li>
                <li><a href="{{ url_for('about') }}" class="active">About</a></li>
                <li><a href="{{ url_for('portfolio') }}">Portfolio</a></li>
                <li><a href="{{ url_for('blog') }}">Blog</a></li>
                <li><a href="{{ url_for('contact') }}">Contact</a></li>
            </ul>
        </nav>
    </header>
    
    <section class="page-header">
        <div class="container">
            <h1>About Me</h1>
            <p>Learn more about my background and expertise</p>
        </div>
    </section>
    
    <section class="about-content">
        <div class="container">
            <div class="about-grid">
                <div class="about-image">
                    <img src="https://via.placeholder.com/600x800?text=Profile+Photo" alt="Profile Photo">
                </div>
                <div class="about-text">
                    <h2>My Story</h2>
                    <p>I am a passionate designer with over 5 years of experience in creating beautiful and functional digital experiences. My journey in design started when I was studying computer science and discovered my passion for creating user-centered interfaces.</p>
                    
                    <p>Since then, I've worked with various clients from startups to established companies, helping them achieve their goals through thoughtful design solutions.</p>
                    
                    <h3>My Approach</h3>
                    <p>I believe that good design is not just about aesthetics but also about solving problems. I approach each project with a focus on understanding the user needs and business goals to create designs that are both beautiful and effective.</p>
                    
                    <h3>Skills</h3>
                    <ul class="skills-list">
                        <li>UI/UX Design</li>
                        <li>Web Design</li>
                        <li>Brand Identity</li>
                        <li>Prototyping</li>
                        <li>User Research</li>
                        <li>HTML/CSS</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    
    <footer>
        <div class="container">
            <p>&copy; 2025 My Creative Portfolio</p>
        </div>
    </footer>
</body>
</html>"""
            
            elif template == 'blog_post.html':
                content = """<!DOCTYPE html>
<html>
<head>
    <title>{{ post.title }} - My Personal Website</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home') }}">Home</a></li>
                <li><a href="{{ url_for('about') }}">About</a></li>
                <li><a href="{{ url_for('portfolio') }}">Portfolio</a></li>
                <li><a href="{{ url_for('blog') }}" class="active">Blog</a></li>
                <li><a href="{{ url_for('contact') }}">Contact</a></li>
            </ul>
        </nav>
    </header>
    
    <article class="blog-post-single">
        <div class="container">
            <div class="post-header">
                <h1>{{ post.title }}</h1>
                <div class="post-meta">
                    <span class="date">{{ post.date }}</span>
                    <span class="author">by {{ post.author }}</span>
                    <span class="categories">
                        {% for category in post.categories %}
                        <a href="{{ url_for('blog_category', category=category) }}">{{ category }}</a>
                        {% if not loop.last %}, {% endif %}
                        {% endfor %}
                    </span>
                </div>
            </div>
            
            <div class="post-featured-image">
                <img src="{{ post.featured_image }}" alt="{{ post.title }}">
            </div>
            
            <div class="post-content">
                {{ post.content | safe }}
            </div>
            
            <div class="post-comments">
                <h3>Comments ({{ post.comments|length }})</h3>
                
                {% if post.comments %}
                <div class="comments-list">
                    {% for comment in post.comments %}
                    <div class="comment">
                        <div class="comment-meta">
                            <span class="comment-author">{{ comment.name }}</span>
                            <span class="comment-date">{{ comment.date }}</span>
                        </div>
                        <div class="comment-content">
                            {{ comment.content }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p>No comments yet. Be the first to comment!</p>
                {% endif %}
                
                <div class="comment-form">
                    <h4>Leave a Comment</h4>
                    <form action="{{ url_for('add_comment', post_id=post.id) }}" method="post">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="content">Comment</label>
                            <textarea id="content" name="content" rows="5" required></textarea>
                        </div>
                        <button type="submit" class="btn">Submit Comment</button>
                    </form>
                </div>
            </div>
        </div>
    </article>
    
    <footer>
        <div class="container">
            <p>&copy; 2025 My Creative Portfolio</p>
        </div>
    </footer>
</body>
</html>"""
            
            elif template == 'contact.html':
                content = """<!DOCTYPE html>
<html>
<head>
    <title>Contact - My Personal Website</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home') }}">Home</a></li>
                <li><a href="{{ url_for('about') }}">About</a></li>
                <li><a href="{{ url_for('portfolio') }}">Portfolio</a></li>
                <li><a href="{{ url_for('blog') }}">Blog</a></li>
                <li><a href="{{ url_for('contact') }}" class="active">Contact</a></li>
            </ul>
        </nav>
    </header>
    
    <section class="page-header">
        <div class="container">
            <h1>Contact Me</h1>
            <p>Get in touch for collaborations or inquiries</p>
        </div>
    </section>
    
    <section class="contact-content">
        <div class="container">
            <div class="contact-grid">
                <div class="contact-info">
                    <h2>Contact Information</h2>
                    <p>Feel free to reach out to me for any design projects, collaborations, or just to say hello!</p>
                    
                    <div class="info-item">
                        <h3>Email</h3>
                        <p><a href="mailto:contact@example.com">contact@example.com</a></p>
                    </div>
                    
                    <div class="info-item">
                        <h3>Phone</h3>
                        <p>+1 (555) 123-4567</p>
                    </div>
                    
                    <div class="info-item">
                        <h3>Social Media</h3>
                        <div class="social-links">
                            <a href="#" class="social-link">Twitter</a>
                            <a href="#" class="social-link">LinkedIn</a>
                            <a href="#" class="social-link">Instagram</a>
                            <a href="#" class="social-link">Dribbble</a>
                        </div>
                    </div>
                </div>
                
                <div class="contact-form">
                    <h2>Send Me a Message</h2>
                    <form action="#" method="post">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" id="subject" name="subject" required>
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea id="message" name="message" rows="5" required></textarea>
                        </div>
                        <button type="submit" class="btn">Send Message</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
    <footer>
        <div class="container">
            <p>&copy; 2025 My Creative Portfolio</p>
        </div>
    </footer>
</body>
</html>"""
            
            elif template == 'portfolio.html':
                content = """<!DOCTYPE html>
<html>
<head>
    <title>Portfolio - My Personal Website</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home') }}">Home</a></li>
                <li><a href="{{ url_for('about') }}">About</a></li>
                <li><a href="{{ url_for('portfolio') }}" class="active">Portfolio</a></li>
                <li><a href="{{ url_for('blog') }}">Blog</a></li>
                <li><a href="{{ url_for('contact') }}">Contact</a></li>
            </ul>
        </nav>
    </header>
    
    <section class="page-header">
        <div class="container">
            <h1>Portfolio</h1>
            <p>Showcasing my design work and projects</p>
        </div>
    </section>
    
    <section class="portfolio-content">
        <div class="container">
            <div class="portfolio-filters">
                <button class="filter-btn active" data-filter="all">All</button>
                <button class="filter-btn" data-filter="Web Design">Web Design</button>
                <button class="filter-btn" data-filter="UI/UX">UI/UX</button>
                <button class="filter-btn" data-filter="Branding">Branding</button>
            </div>
            
            <div class="portfolio-grid">
                {% for item in portfolio_items %}
                <div class="portfolio-item" data-category="{{ item.category }}">
                    <div class="portfolio-image">
                        <img src="{{ item.image }}" alt="{{ item.title }}">
                        <div class="portfolio-overlay">
                            <h3>{{ item.title }}</h3>
                            <p>{{ item.category }}</p>
                            <a href="{{ url_for('portfolio_item', item_id=item.id) }}" class="btn">View Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    
    <footer>
        <div class="container">
            <p>&copy; 2025 My Creative Portfolio</p>
        </div>
    </footer>
    
    <script>
        // Simple portfolio filtering
        document.addEventListener('DOMContentLoaded', function() {
            const filterBtns = document.querySelectorAll('.filter-btn');
            const portfolioItems = document.querySelectorAll('.portfolio-item');
            
            filterBtns.forEach(btn => {
                btn.addEventListener('click', function() {
                    // Remove active class from all buttons
                    filterBtns.forEach(btn => btn.classList.remove('active'));
                    
                    // Add active class to clicked button
                    this.classList.add('active');
                    
                    const filter = this.getAttribute('data-filter');
                    
                    portfolioItems.forEach(item => {
                        if (filter === 'all' || item.getAttribute('data-category') === filter) {
                            item.style.display = 'block';
                        } else {
                            item.style.display = 'none';
                        }
                    });
                });
            });
        });
    </script>
</body>
</html>"""
            
            elif template == 'portfolio_item.html':
                content = """<!DOCTYPE html>
<html>
<head>
    <title>{{ item.title }} - My Personal Website</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home') }}">Home</a></li>
                <li><a href="{{ url_for('about') }}">About</a></li>
                <li><a href="{{ url_for('portfolio') }}" class="active">Portfolio</a></li>
                <li><a href="{{ url_for('blog') }}">Blog</a></li>
                <li><a href="{{ url_for('contact') }}">Contact</a></li>
            </ul>
        </nav>
    </header>
    
    <section class="portfolio-item-single">
        <div class="container">
            <div class="portfolio-header">
                <h1>{{ item.title }}</h1>
                <div class="portfolio-meta">
                    <span class="category">{{ item.category }}</span>
                    <span class="client">Client: {{ item.client }}</span>
                    <span class="date">Date: {{ item.date }}</span>
                </div>
            </div>
            
            <div class="portfolio-featured-image">
                <img src="{{ item.image }}" alt="{{ item.title }}">
            </div>
            
            <div class="portfolio-description">
                <h2>Project Description</h2>
                <p>{{ item.description }}</p>
                
                <h2>Project Details</h2>
                <ul class="project-details">
                    <li><strong>Client:</strong> {{ item.client }}</li>
                    <li><strong>Category:</strong> {{ item.category }}</li>
                    <li><strong>Date:</strong> {{ item.date }}</li>
                </ul>
                
                <div class="project-navigation">
                    <a href="{{ url_for('portfolio') }}" class="btn">Back to Portfolio</a>
                </div>
            </div>
        </div>
    </section>
    
    <footer>
        <div class="container">
            <p>&copy; 2025 My Creative Portfolio</p>
        </div>
    </footer>
</body>
</html>"""
            
            with open(os.path.join(templates_dir, template), 'w') as f:
                f.write(content)
    
    print("✅ All template files created successfully")

def run_blog_app():
    """Run the Flask blog application"""
    print("Starting the Flask blog application...")
    
    try:
        from app import app
        
        app.run(debug=True, host='0.0.0.0', port=5000)
    except Exception as e:
        print(f"❌ Error starting the Flask application: {str(e)}")
        sys.exit(1)

def main():
    """Main function to deploy the blog"""
    print("\n🚀 Deploying Expeta-generated Blog Website")
    print("=" * 80)
    
    setup_sample_data()
    
    create_missing_templates()
    
    print("\n✅ Blog deployment complete!")
    print("=" * 80)
    print("To view the blog, open your browser and navigate to: http://localhost:5000")
    print("Press Ctrl+C to stop the server when done.")
    print("=" * 80)
    
    run_blog_app()

if __name__ == "__main__":
    main()
